### ISSUE TITLE
App Force Close when running

### ISSUE THREAD

**Issue by abdhilabs** [Andre-max/Kotlin-Weather-App#3]
I just found an error, when I run the app firstly

2020-10-17 11:51:27.511 13501-13501/com.example.kotlinweatherapp.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kotlinweatherapp.debug, PID: 13501
    com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.data
        at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:162)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:68)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by Andre-max** [comment]
> I just found an error, when I run the app firstly
> 
> 2020-10-17 11:51:27.511 13501-13501/com.example.kotlinweatherapp.debug E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.example.kotlinweatherapp.debug, PID: 13501
> com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.data
> at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:162)
> at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:68)
> at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
> at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
> at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
> at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
> at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
> at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
> at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
> at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:919)

Which fragment causes the crash. Is it the current weather forecast, future weather forecast, search location fragment or the settings fragment ?
